In [1]:
# K-FOLD ALGORITHM EXERCISE

In [2]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
digits = load_digits()

###### THE PROBLEM WITH train_test_split METHOD IS THAT SOMETIMES IT DOESN'T DISTRIBUTE THE DATA IN VARIATION AS A RESULT EVERY TIME MODELS SCORE CHANGES i.e. ITS SHOWS REFLECTION ON MODEL ACCURACY => TO RESOLVE THIS PROBLEM WE HAVE 'K-Fold ALGORITHM'.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [5]:
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9703703703703703

In [6]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8203703703703704

In [7]:
model = SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9925925925925926

In [8]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9833333333333333

###### SOLUTION

###### 1.) TYPICAL WAY OF COMPARING MODEL ACCURACY

In [9]:
from sklearn.model_selection import KFold

In [10]:
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [11]:
for train, test in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train, test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [12]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
score_linr = []
score_logr = []
score_dt = []
score_svc = []
score_rfc = []
# score = {}

for train, test in skf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train], digits.data[test], digits.target[train], digits.target[test]
    score_linr.append(get_score(LinearRegression(), X_train, X_test, y_train, y_test))
    score_logr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    score_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))
    score_svc.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rfc.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
#     score['score'] = {
#         "logistic_score" : score_lr,
#         "decision_tree_score" : score_dt,
#         "svm_score" : score_svc,
#         "random_forest_score" : score_rfc
#     }

In [15]:
print("LINEAR REGRESSION SCORE = \n", score_linr)
print()
print("LOGISTIC REGRESSION SCORE = \n", score_logr)
print()
print("Decision TREE SCORE = \n", score_dt)
print()
print("SVM SCORE = \n", score_svc)
print()
print("RANDOM FOREST SCORE = \n", score_rfc)

LINEAR REGRESSION SCORE = 
 [0.5170851293958866, 0.5656905210689886, 0.4196685566691414]

LOGISTIC REGRESSION SCORE = 
 [0.9248747913188647, 0.9415692821368948, 0.9232053422370617]

Decision TREE SCORE = 
 [0.7462437395659433, 0.8263772954924875, 0.7746243739565943]

SVM SCORE = 
 [0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

RANDOM FOREST SCORE = 
 [0.9382303839732888, 0.9599332220367279, 0.9348914858096828]


###### 2.) EASIEST WAY OF COMPARING MODEL ACCURACY

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(LinearRegression(), digits.data, digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [17]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])

In [18]:
cross_val_score(DecisionTreeClassifier(), digits.data, digits.target)

array([0.77777778, 0.72222222, 0.80501393, 0.8356546 , 0.78551532])

In [19]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [20]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.88333333, 0.95543175, 0.95264624, 0.92200557])